# Numpy

In [50]:
import numpy as np
arr1d = np.array([1, 2, 3, 4, 5])
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr1d) 
print(arr2d.shape) 
print(arr1d[1:4])  
print(arr2d[0:2, 1:3])  
arr3 = np.array([2, 4, 6, 8, 10])
print(arr1d + arr3)  
print(np.dot(arr1d , arr3))
print(np.mean(arr2d)) 
print(np.max(arr1d)) 

[1 2 3 4 5]
(3, 3)
[2 3 4]
[[2 3]
 [5 6]]
[ 3  6  9 12 15]
110
5.0
5


# Pandas

In [56]:
import pandas as pd

# create a DataFrame with some sample data
data = {
    'name': ['Alice', 'Bob', 'Hari', 'Dave', 'Eva'],
    'age': [25, 32, 18, 47, 29],
    'gender': ['F', 'M', 'M', 'M', 'F'],
    'city': ['New York', 'San Francisco', 'Chicago', 'Los Angeles', 'Boston']
}
df = pd.DataFrame(data)

# print the first few rows of the DataFrame
print(df.head())

# print the data types of each column
print(df.dtypes)

# print some basic statistics for the numerical columns
print(df.describe())

# filter the DataFrame to only include rows where age is greater than 30
filtered_df = df[df['age'] > 30]

# group the DataFrame by gender and calculate the mean age for each group
grouped_df = df.groupby('gender')['age'].mean()
print(grouped_df)
# export the DataFrame to a CSV file
df.to_csv('names.csv', index=False)

data =pd.read_csv('names.csv')
print(data)

    name  age gender           city
0  Alice   25      F       New York
1    Bob   32      M  San Francisco
2   Hari   18      M        Chicago
3   Dave   47      M    Los Angeles
4    Eva   29      F         Boston
name      object
age        int64
gender    object
city      object
dtype: object
             age
count   5.000000
mean   30.200000
std    10.756393
min    18.000000
25%    25.000000
50%    29.000000
75%    32.000000
max    47.000000
gender
F    27.000000
M    32.333333
Name: age, dtype: float64
    name  age gender           city
0  Alice   25      F       New York
1    Bob   32      M  San Francisco
2   Hari   18      M        Chicago
3   Dave   47      M    Los Angeles
4    Eva   29      F         Boston


# Scipy

In [3]:
import numpy as np
from scipy import stats

# create a sample of normally distributed data
data = np.random.normal(size=100)

# calculate basic statistics
mean = np.mean(data)
std = np.std(data)
median = np.median(data)

# perform hypothesis testing
t_stat, p_val = stats.ttest_1samp(data, 0)

# print out results
print("Mean:", mean)
print("Standard deviation:", std)
print("Median:", median)
print("T-statistic:", t_stat)
print("P-value:", p_val)

Mean: -0.025304851647780784
Standard deviation: 0.8810219808453319
Median: -0.009372071876852475
T-statistic: -0.28578185374252046
P-value: 0.7756423109797927


# Tensorflow

In [10]:
import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
# create two constant tensors to perform matrix multiplication
a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
b = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# perform matrix multiplication
c = tf.matmul(a, b)

# create a session to run the graph
with tf.compat.v1.Session() as sess:
    # run the graph and print the result
    result = sess.run(c)
    print(result)

[[19. 22.]
 [43. 50.]]
